### ISSUE TITLE
No package matching 'chromium-common' is available

### ISSUE THREAD

**Issue by cubistico** [bodsch/ansible-chromium-headless#2]
I get 

`No package matching 'chromium-common' is available`

when trying to install on Ubuntu 22.04.1

**Comment by bodsch** [comment]
Ubuntu 22.x is not in the test matrix.
I'll be happy to take a look at it, though.

**Comment by bodsch** [comment]
fixed with release [1.2.0](https://github.com/bodsch/ansible-chromium-headless/releases/tag/1.2.0).

Please try again.

For the record: I am not a fan of snapd and will not guarantee to support for it in the future!
